### ISSUE TITLE
Having trouble building from source

### ISSUE THREAD

**Issue by BrendanMulcahy** [oshvartz/tpldataflow-debuggervisualizer#1]
Hello,

I could really use a tool like this but I can't get this to build locally since I am missing the wixproj.  Can you describe how to add these dependencies?

Could you add your VS 2017 updates to the marketplace?  The previous 2015 version does not seem to install correctly.  Whenever I run the msi, it doesn't actually install the extension.

Thanks,
Brendan

Update:
I installed wix project dependencies and got the build working; however, whenever I run the msi it generates, nothing happens.  Nothing is getting added to visual studio (seems to crash part way through).

**Comment by oshvartz** [comment]
Hi Berndan
I didn't upload it to the market yet but I can send you the installer all that it does is adding files to 
VS 2017 installation folder\Common7\Packages\Debugger\Visualizers
please try to run it and see if the files are copied to this folder and it works for you
[TPLDataFlowDebuggerVisualizerSetup.zip](https://github.com/oshvartz/tpldataflow-debuggervisualizer/files/1575937/TPLDataFlowDebuggerVisualizerSetup.zip)

Update me
Thanks,
 Offir

**Comment by oshvartz** [comment]
I uploaded vs 2017 version to the market place at:
[here](https://marketplace.visualstudio.com/items?itemName=OffirShvartz.TPLDataFlowDebuggerVisualizer2017)

**Comment by BrendanMulcahy** [comment]
Awesome!  Thanks for the hard work.  I am on vacation but when I return to the office in January I will let you know if it's all working smoothly.

**Comment by BrendanMulcahy** [comment]
Hey, I just wanted to let you know that I finally got around to testing this and it looks great!  Thanks for your hard work!
